#!/bin/bash

SRC_BASE_DIR=../strut-engine/app/**/*.js
JS2COFFEE=~/node_modules/js2coffee/bin/js2coffee
 
for file in $SRC_BASE_DIR 
do
  echo "${file%.js}.coffee"
  echo js2coffee -i4 -sq --verbose $file > "${file%.js}.coffee"
  js2coffee -i4 -sq --verbose $file > "${file%.js}.coffee"
done
